# custom_header_signature
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'voice_v2/client.rb'

# Models
require_relative 'voice_v2/models/base_model.rb'
require_relative 'voice_v2/models/api_call_response.rb'
require_relative 'voice_v2/models/api_create_call_request.rb'
require_relative 'voice_v2/models/api_modify_call_request.rb'
require_relative 'voice_v2/models/answer_method_enum.rb'
require_relative 'voice_v2/models/disconnect_method_enum.rb'
require_relative 'voice_v2/models/redirect_method_enum.rb'
require_relative 'voice_v2/models/state_enum.rb'

# Controllers
require_relative 'voice_v2/controllers/base_controller.rb'
require_relative 'voice_v2/controllers/calls' \
                 '_controller.rb'

# BXML
require_relative 'voice_v2/bxml/ruby_bandwidth_bxml.rb'