# custom_header_signature
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CombinedSdk
  module CustomHeaderSignature
    #  custom_header_signature client class.
    class Client
      attr_reader :config

      # Access to custom_header_signature controller.
      # @return [CustomHeaderSignatureController] Returns the controller instance.
      def custom_header_signature
        @custom_header_signature ||= CustomHeaderSignatureController.new config
      end

      def initialize(timeout: 60, max_retries: 0, retry_interval: 1,
                     backoff_factor: 1, environment: Environment::TESTING,
                     port: '80', suites: SuiteCodeEnum::HEARTS, token: '',
                     config: nil)
        @config = if config.nil?
                    Configuration.new(timeout: timeout, max_retries: max_retries,
                                      retry_interval: retry_interval,
                                      backoff_factor: backoff_factor,
                                      environment: environment, port: port,
                                      suites: suites, token: token)
                  else
                    config
                  end
      end
    end
  end
end