# custom_header_signature
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'custom_header_signature/client.rb'

# Controllers
require_relative 'custom_header_signature/controllers/base_controller.rb'
require_relative 'custom_header_signature/controllers/custom_header_signature' \
                 '_controller.rb'
