# calc
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CombinedSdk
  module Calc
    #  calc client class.
    class Client
      attr_reader :config

      # Access to simple_calculator controller.
      # @return [SimpleCalculatorController] Returns the controller instance.
      def simple_calculator
        @simple_calculator ||= SimpleCalculatorController.new config
      end

      def initialize(timeout: 60, max_retries: 0, retry_interval: 1,
                     backoff_factor: 1, environment: Environment::PRODUCTION,
                     config: nil)
        @config = if config.nil?
                    Configuration.new(timeout: timeout, max_retries: max_retries,
                                      retry_interval: retry_interval,
                                      backoff_factor: backoff_factor,
                                      environment: environment)
                  else
                    config
                  end
      end
    end
  end
end