# custom_header_signature
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  module VoiceV2
    #  custom_header_signature client class.
    class Client
      attr_reader :config

      # Access to custom_header_signature controller.
      # @return [CustomHeaderSignatureController] Returns the controller instance.
      def calls
        @calls ||= CallsController.new config
      end

      def initialize(timeout: 60, max_retries: 0, retry_interval: 1,
                     backoff_factor: 1, environment: Environment::PRODUCTION,
                     voice_v2_basic_auth_user_name: 'TODO: Replace',
                     voice_v2_basic_auth_password: 'TODO: Replace',
                     config: nil)
        @config = if config.nil?
                    Configuration.new(timeout: timeout, max_retries: max_retries,
                                      retry_interval: retry_interval,
                                      backoff_factor: backoff_factor,
                                      environment: environment,
                                      voice_v2_basic_auth_user_name: voice_v2_basic_auth_user_name,
                                      voice_v2_basic_auth_password: voice_v2_basic_auth_password)
                  else
                    config
                  end
      end
    end
  end
end
