# calc
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'calc/client.rb'

# Models
require_relative 'calc/models/operation_type_enum.rb'

# Exceptions
require_relative 'calc/exceptions/could_not_compute_exception.rb'

# Controllers
require_relative 'calc/controllers/base_controller.rb'
require_relative 'calc/controllers/simple_calculator_controller.rb'
