# calc
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  class Client
    attr_reader :config

    def voice_v2_client
      @voice_v2_client ||= VoiceV2::Client.new(config: config)
    end

    def initialize(timeout: 60, max_retries: 0, retry_interval: 1,
                   backoff_factor: 1,environment: Environment::PRODUCTION,
                   voice_v2_basic_auth_user_name: 'TODO: Replace',
                   voice_v2_basic_auth_password: 'TODO: Replace')
      @config = if config.nil?
                  Configuration.new(timeout: timeout, max_retries: max_retries,
                                    retry_interval: retry_interval,
                                    backoff_factor: backoff_factor,
                                    environment: environment,
                                    voice_v2_basic_auth_user_name: voice_v2_basic_auth_user_name,
                                    voice_v2_basic_auth_password: voice_v2_basic_auth_password)
                else
                  config
                end
    end
  end
end