# calc
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CombinedSdk
  class Client
    attr_reader :config

    def ba_tester_client
      @ba_tester_client ||= BaTester::Client.new(config: config)
    end

    def calc_client
      @calc_client ||= Calc::Client.new(config: config)
    end

    def custom_header_signature_client
      @custom_header_signature_client ||= CustomHeaderSignature::Client.new(config: config)
    end

    def initialize(timeout: 60, max_retries: 0, retry_interval: 1,
                   backoff_factor: 1, environment: Environment::PRODUCTION,
                   port_ba: '80', suit_ba: 1,
                   port_chs: '80', suit_chs: 1, token: '',
                   basic_auth_user_name: 'TODO: Replace',
                   basic_auth_password: 'TODO: Replace')
      @config = if config.nil?
                  Configuration.new(timeout: timeout, max_retries: max_retries,
                                    retry_interval: retry_interval,
                                    backoff_factor: backoff_factor,
                                    environment: environment,
                                    port_ba: port_ba, suit_ba: suit_ba,
                                    port_chs: port_chs, suit_chs: suit_chs,
                                    token: token,
                                    basic_auth_user_name: basic_auth_user_name,
                                    basic_auth_password: basic_auth_password)
                else
                  config
                end
    end
  end
end