# voice_v2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).
module Bandwidth
	module VoiceV2
	  # State.
	  class StateEnum
	    STATE_ENUM = [
	      # TODO: Write general description for ACTIVE
	      ACTIVE = 'ACTIVE'.freeze,

	      # TODO: Write general description for COMPLETED
	      COMPLETED = 'COMPLETED'.freeze
	    ].freeze
	  end
	end
end